[Book_Store] added shopping cart
fedorovychh/book-store pull request #10
Opened 2023-12-28 14:24 UTC by fedorovychh

- created new models
- created their dtos
- created mappers
- created services
- created repositories
- implemented feature than creates shopping cart for user during registration
- created new changesets to liquibase
- created controller for shopping cart with it's endpoints

2023-12-29 16:22 UTC, bhdnchui requested changes
A few points to consider.

2023-12-29 16:22 UTC, bhdnchui commented on src/main/java/com/app/bookstore/controller/ShoppingCartController.java
> +    private Long getUserId(Authentication authentication) {
It's unnecessary to make a separate method if you use it one time.

2023-12-29 16:22 UTC, bhdnchui commented on src/main/java/com/app/bookstore/controller/ShoppingCartController.java
> +    private Long getUserId(Authentication authentication) {
It's unnecessary to make a separate method if you use it one time.

2023-12-29 16:22 UTC, bhdnchui commented on src/main/java/com/app/bookstore/dto/cart/item/AddCartItemRequestDto.java
> +    private Integer quantity;
Add constraints here.

2023-12-29 16:22 UTC, bhdnchui commented on src/main/java/com/app/bookstore/repository/cart/item/CartItemRepository.java
> +    @Query("SELECT b FROM CartItem b JOIN FETCH b.shoppingCart")
Why do you use `b` here?

2023-12-29 16:22 UTC, bhdnchui commented on src/main/java/com/app/bookstore/repository/cart/item/CartItemRepository.java
> +    @Query("SELECT b FROM CartItem b JOIN fetch b.shoppingCart c WHERE c.id = :itemId")
One random letter naming

2023-12-29 16:22 UTC, bhdnchui commented on src/main/java/com/app/bookstore/service/cart/item/CartItemServiceImpl.java
> +    private CartItem parseCartItem(Long cartItemId) {
Rename. You did not parse anything here.

2023-12-29 16:22 UTC, bhdnchui commented on src/main/java/com/app/bookstore/service/cart/item/CartItemServiceImpl.java
> +    public CartItemResponseDto updateCartItemById(Long cartItemId, int quantity) {
If it is CartItemService, than we can avoid using CardItem in methods.
```suggestion
    public CartItemResponseDto updateById(Long id, int quantity) {

```

2023-12-29 16:22 UTC, bhdnchui commented on src/main/java/com/app/bookstore/service/cart/item/CartItemServiceImpl.java
> +    public CartItemResponseDto updateCartItemById(Long cartItemId, int quantity) {
Make sure to simplify it everywhere.

2023-12-29 16:22 UTC, bhdnchui commented on src/main/java/com/app/bookstore/service/shopping/cart/ShoppingCartService.java
> +    ShoppingCartResponseDto findShoppingCartByUserId(Long userId);
Same as for CardItemService.
```suggestion
    ShoppingCartResponseDto findByUserId(Long userId);
```

2023-12-29 16:22 UTC, bhdnchui commented on src/main/java/com/app/bookstore/service/shopping/cart/ShoppingCartService.java
> +    ShoppingCartResponseDto findShoppingCartByUserId(Long userId);
Make sure to simplify it everywhere.

2023-12-29 16:22 UTC, bhdnchui commented on src/main/java/com/app/bookstore/repository/shopping/cart/ShoppingCartRepository.java
> +    ShoppingCart findShoppingCartByUserId(Long userId);
Return `Optional` here

2024-01-02 13:38 UTC, vovasalyha approved these changes

2024-01-02 18:37 UTC, merged