[Book_Store] order functionality
fedorovychh/book-store pull request #11
Opened 2024-01-03 20:32 UTC by fedorovychh

Added Order functionality:
- controller
- Order entity
- OrderItem entity
- services
- dtos
- repositories
- added liquibase changeset
- mappers

2024-01-03 20:51 UTC, dima-semeniuk approved these changes
Great job! I have nothing to fix)

2024-01-04 09:16 UTC, d1sam requested changes
good job, but there are some changes should be done!

2024-01-04 09:16 UTC, d1sam commented on src/main/java/com/app/bookstore/model/Order.java
add `nullable = false` to fields

2024-01-04 09:16 UTC, d1sam commented on src/main/java/com/app/bookstore/service/order/OrderServiceImpl.java
> +    public OrderResponseDto updateStatus(Long id, UpdateOrderRequestDto requestDto) {
```suggestion
    @Transactional
    public OrderResponseDto updateStatus(Long id, UpdateOrderRequestDto requestDto) {

```

2024-01-04 09:16 UTC, d1sam commented on src/main/java/com/app/bookstore/service/order/OrderServiceImpl.java
> +    public OrderResponseDto placeOrder(User user, OrderRequestDto requestDto) {
```suggestion
    public OrderResponseDto placeOrder(Long userId, OrderRequestDto requestDto) {

```

2024-01-04 09:16 UTC, d1sam commented on src/main/java/com/app/bookstore/service/order/OrderServiceImpl.java
> +    private Order createOrder(User user, ShoppingCart shoppingCart, OrderRequestDto requestDto) {
```suggestion
    private Order createOrder(Long userId, ShoppingCart shoppingCart, OrderRequestDto requestDto) {

```

2024-01-04 10:24 UTC, fedorovychh commented on src/main/java/com/app/bookstore/service/order/OrderServiceImpl.java
> +    private Order createOrder(User user, ShoppingCart shoppingCart, OrderRequestDto requestDto) {
I set user to the order in this method, so I can't change it

2024-01-04 10:25 UTC, fedorovychh commented on src/main/java/com/app/bookstore/service/order/OrderServiceImpl.java
> +    public OrderResponseDto placeOrder(User user, OrderRequestDto requestDto) {
I set user to the order in this method, so I can't change it

2024-01-04 13:27 UTC, vovasalyha approved these changes

2024-01-04 13:29 UTC, merged