[Book_Store] tests for shopping cart added
fedorovychh/book-store pull request #15
Opened 2024-01-09 18:46 UTC by fedorovychh

- test for service
- test for repository
- test for controller
additionally changed input param in ShoppingCartController methods: changed authentication to userId

2024-01-09 19:31 UTC, vadymhrnk approved these changes
LGTM, good job!

2024-01-11 11:35 UTC, yevheniisynytsia requested changes
Well done! added some small comments

2024-01-11 11:35 UTC, yevheniisynytsia commented on src/test/java/com/app/bookstore/controller/ShoppingCartControllerTest.java
> +    private static final String URL_BOOKS = "/cart";
firstly, it is not books url, secondly, it is not worth moving to constant as you are not reusing this string in other places

2024-01-11 11:35 UTC, yevheniisynytsia commented on src/test/java/com/app/bookstore/controller/ShoppingCartControllerTest.java
> +                ShoppingCartResponseDto.class);
add separations with empty lines so that you have mockmvc.perform - expected/actual - assertion parts

2024-01-11 11:35 UTC, yevheniisynytsia commented on src/test/java/com/app/bookstore/service/shopping/cart/ShoppingCartServiceImplTest.java
> +    private static User user;
place them before mocks and tested service.
I prefer having the tested service to be the last field in the class

2024-01-11 11:35 UTC, yevheniisynytsia commented on src/test/java/com/app/bookstore/service/shopping/cart/ShoppingCartServiceImplTest.java
> +        Mockito.when(shoppingCartRepository.findByUserId(user.getId()))
let's add static import

2024-01-15 07:40 UTC, yevheniisynytsia approved these changes

2024-01-15 17:15 UTC, merged