[Book_Store] added readme file
fedorovychh/book-store pull request #17
Opened 2024-01-13 12:31 UTC by fedorovychh

2024-01-15 10:24 UTC, d1sam requested changes

2024-01-15 10:24 UTC, d1sam commented on README.md
Elaborate on how someone can set up or use your project. This is a very important part

2024-01-17 06:53 UTC, yevheniisynytsia approved these changes

2024-01-17 06:53 UTC, yevheniisynytsia commented on README.md
> +  <summary>Update existing category</summary>
```suggestion
  <summary>Update existing order</summary>

```

2024-01-17 09:00 UTC, merged