[Book_Store] added new entity Category
fedorovychh/book-store pull request #9
Opened 2023-12-24 14:47 UTC by fedorovychh

added new entity Category:
- controller
- dtos
- service
- repository
- mapper

2023-12-26 13:03 UTC, andrii-hoienko requested changes
GJ, but some improvements required

2023-12-26 13:03 UTC, andrii-hoienko commented on src/main/java/com/app/bookstore/dto/book/BookDtoWithoutCategoryIds.java
> +public class BookDtoWithoutCategoryIds {
To avoid code duplication it makes sence to inherit BookDto from BookDtoWithoutCategoryIds

2023-12-26 13:03 UTC, andrii-hoienko commented on src/main/java/com/app/bookstore/model/Book.java
> +    private Set<Category> categories = new HashSet<>();
Better to exclude this field from equals/hash code and toString

2023-12-26 13:03 UTC, andrii-hoienko commented on src/main/java/com/app/bookstore/service/book/BookServiceImpl.java
> +        Category category = categoryRepository.findById(id)
Please move logic that interacts with categoryRepository to categoryService to meet the single responsibility principle

2023-12-26 13:03 UTC, andrii-hoienko commented on src/main/java/com/app/bookstore/service/book/BookServiceImpl.java
> +        return bookRepository.getBooksByCategoriesContaining(category).stream()
Is it possible to search by category ID, not by category object itself? It will allow to removal of logic of searching category

2023-12-26 13:19 UTC, fedorovychh commented on src/main/java/com/app/bookstore/dto/book/BookDtoWithoutCategoryIds.java
> +public class BookDtoWithoutCategoryIds {
Got it

2023-12-27 10:32 UTC, d1sam approved these changes
Good job, but please pay attention, that better to use `valueComputed` with `preConditions` instead of hard-coded values.

2023-12-27 10:32 UTC, d1sam commented on src/main/java/com/app/bookstore/dto/book/CreateBookRequestDto.java
>      @NotNull
```suggestion
    @NotBlank
```

2023-12-27 10:32 UTC, d1sam commented on src/main/java/com/app/bookstore/dto/book/CreateBookRequestDto.java
>      @NotNull
```suggestion
    @NotBlank
```

2023-12-27 10:32 UTC, d1sam commented on src/main/resources/db/changelog/changes/11-insert-admin-relation-to-users_roles.yaml
better to use `valueComputed` with `preConditions` instead of hard-coded values.

2023-12-27 10:32 UTC, d1sam commented on src/main/resources/db/changelog/changes/16-insert-books_categories-relations.yaml
better to use `valueComputed` with `preConditions` instead of hard-coded values.

2023-12-28 07:48 UTC, merged